#pragma once

enum STATUS_CODE{
    SUCCESS,
    NO_FILE_OPEN,
    NO_FILE_FOUND,
    BAD_FILE_MODE,
    BAD_TYPE,
    BAD_ARG,
    BAD_NAME_LENGTH,
    CASTING_ERROR,
    BOUNDS_ERROR,
    ILLEGAL_ACCESS,
    OUT_OF_MEMORY
};